name: 'Check unlabeled issues'
on:
    push:
        branches: [main]

jobs:
  check-unlabeled-issues:
    runs-on: ubuntu-latest

    permissions:
      issues: write  # Moved here to limit the scope to this job only

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Check for unlabeled issues
        run: bash ./tools/check-unlabeled-issues.sh
